#!/usr/bin/env bash

ensure package chruby
ensure package ruby-install

source "$(brew --prefix chruby)/share/chruby/chruby.sh"

installed="";

if [ -n "$2" ]; then
  engine="$1";
  target="$2";
else
  engine="ruby"
  target=$1;
fi

if ! $(ls "$HOME/.rubies/$engine-$target" &>/dev/null); then
  ruby-install "$engine" "$target";
fi
