#!/usr/bin/env bash

set -e

source "$ENSURE_LIB/helpers.sh"

plugin="$1";
name="${plugin##*/}"

[ -n "$plugin" ] || abort "Usage: ensure vim-plugin <user>/<repo>"

ensure vim-pathogen
ensure git "https://github.com/$plugin" "$HOME/.vim/bundle/$name"
