#!/usr/bin/env bash

app="$1";

for arg in $@; do
  [ "$arg" = "--copy" ] && copy="yes";
done

if [ -n "$(brew cask info "$app" | grep "Not installed")" ]; then
  echo ">> Installing ${app}";

  brew cask install $app;

  if [ -n "$copy" ]; then
    prefix="/opt/homebrew-cask/caskroom/${app}/latest"
    app_path="$(find "$prefix" -iname '*.app' -depth 1)"
    app_name="$(basename "$app_path")"
    rm -f "$HOME/Applications/$app_name"
    cp -r "$app_path" "$HOME/Applications/$app_name"
  fi
fi
