#!/usr/bin/env bash

gem="$1";
version="$2";

[ -z "$gem" ] && {
  echo "Need a gem name. Call as \`ensure gem <gem-name> [<version>]\`." >&2;
  exit 1;
}

installed="$(ruby -e "puts 'yes' if Gem::Specification.any? { |g| g.name == ARGV[0] && (ARGV[1].to_s.empty? ? true : g.version.to_s == ARGV[1]) }" "$gem" "$version")"

if [ -z "$installed" ]; then
  [ -n "$version" ] && version=":$version";
  gem install "${gem}${version}";
fi
