#!/usr/bin/env bash

source "$(dirname $0)/../../lib/ensure/variables.sh"

if [ -f "$ENSURE_MANIFEST" ]; then
  source "$ENSURE_MANIFEST";
else
  echo "Can't find ensure manifest at \"${ENSURE_MANIFEST}\"" >&2
fi
