#!/usr/bin/env bash

source "$(dirname $0)/../../lib/ensure/variables.sh"

if ! $(grep -q "ensure $@" "$ENSURE_MANIFEST" &>/dev/null); then
  echo "ensure $@" >> "$ENSURE_MANIFEST"
  exec ensure $@
fi
