#!/usr/bin/env bash

repo=$1
path=$2

[[ -z "$repo" || -z "$path" ]] && {
  echo "Usage: ensure git <repo> <path>" >&2
  exit 1
}

if [ -d "$path/.git" ]; then
  GIT_DIR="$path/.git" git pull >/dev/null
else
  git clone "$repo" "$path"
fi
