#!/usr/bin/env bash

plugin="$1";
name="${plugin##*/}"

[ -z "$plugin" ] && {
  echo "Usage: ensure vim-plugin <user>/<repo>" >&2
  exit 1
}

ensure vim-pathogen
ensure git "https://github.com/$plugin" "$HOME/.vim/bundle/$name"
