#!/usr/bin/env sh

set -e

source "$ENSURE_LIB/helpers.sh"

expected="$1"
user="${2:-$USER}"

[ -x "$expected" ] || abort "No such shell: $expected";

[ "$SHELL" = "$expected" ] || (
  log_info "Setting $user's shell to $expected";
  sudo chsh -s "$expected" "$user";
)
