#!/usr/bin/env bash

set -e

source "$ENSURE_LIB/helpers.sh"

ensure rbenv
ensure package ruby-build

eval "$(rbenv init -)";

version="$1";
shift

[ -n "$version" ] || abort "Need to declare a version: ensure ruby <version>"

log_info "Installing ruby $version"
if ! $(rbenv versions | grep -q "\b${version}\b"); then
  rbenv install "$version" $@ 2>&1 >$ENSURE_OUTPUT;
else
  log_debug "Skipping ruby $version; already installed"
fi
