#!/bin/sh

set -e

source "$ENSURE_LIB/helpers.sh"

package="$1";
[ -n "$package" ] || abort "Need to declare a package: ensure package <package>"

ensure brew

brew_args="$package";
shift

for arg in $@; do
  if [ -n "$capture" ]; then
    brew_args="$brew_args $arg";
  else
    [ "$arg" = "--" ] && capture="yes";
    [ "$arg" = "--link" ] && link="yes";
    [ "$arg" = "--service" ] && service="yes";
  fi
done

log_info "Installing homebrew package: $package"
if ! $(brew ls --versions "$package" &>/dev/null); then
  brew install $brew_args &>$ENSURE_OUTPUT;
else
  log_debug "Skipping ${package}; already installed"
fi

if [ -n "$link" ]; then
  log_info "Linking $package"
  brew unlink $package >/dev/null;
  brew link --force $package &>$ENSURE_OUTPUT;
fi

if [ -n "$service" ]; then
  log_info "Starting service for $package"
  brew services start "$package" &>$ENSURE_OUTPUT;
fi
