#!/bin/sh

set -e

source "$ENSURE_LIB/helpers.sh"

plugin="$1";
name="${plugin##*/}"

[ -n "$plugin" ] || abort "Usage: ensure vim-plugin <user>/<repo>"

ensure download "$HOME/.vim/autoload/pathogen.vim" "https://tpo.pe/pathogen.vim"
ensure git "https://github.com/$plugin" "$HOME/.vim/bundle/$name"
