#!/usr/bin/env bash

package="$1";
[ -n "$package" ] || (
  echo "Need to declare a package: ensure package <package>" 1>&2;
  exit 1;
)

ensure brew

brew_args="$package";
shift

for arg in $@; do
  if [ -n "$capture" ]; then
    brew_args="$brew_args $arg";
  else
    [ "$arg" = "--" ] && capture="yes";
    [ "$arg" = "--link" ] && link="yes";
    [ "$arg" = "--service" ] && service="yes";
  fi
done

if [ -n "$(brew info "$package" | grep "Not installed")" ]; then
  echo ">> Installing ${package}"

  brew install $brew_args;

  if [ -n "$link" ]; then
    brew unlink $package >/dev/null;
    brew link --force $package >/dev/null;
  fi

  if [ -n "$service" ]; then
    brew services start "$package";
  fi
fi
